### PR TITLE
add slug for transliterate and lowercase letter in urls

### PR DESCRIPTION
**Pull request by nlevchuk**
Hello
I need to use transliterations and lowercase letters in urls for all languages, especially english and russian. I think it's correct solution in terms of SEO

### CODE REVIEW

**Comment by nlevchuk** [comment]
If you haven't any questions I hope you can release new version ASAP. Thanks

**Comment by nlevchuk** [comment]
@lingz please reply for this PR

**Comment by grishinoleg** [comment]
this one can't merge automatically either. can you fix it?

**Comment by nlevchuk** [comment]
yep. give me 5 minutes

**Comment by grishinoleg** [comment]
No probs

**Comment by nlevchuk** [comment]
@grishinoleg done

**Comment by nlevchuk** [comment]
@grishinoleg can you bump version after merged?

**Comment by grishinoleg** [comment]
will bump the version

**Comment by nlevchuk** [comment]
@grishinoleg push the new version to rubygems?

**Comment by grishinoleg** [comment]
@nlevchuk yeah, i just realized that i don't have the rubygems credentials. i'll try to reach Ling and ask him to push it there or give me the credentials. sorry

**Comment by nlevchuk** [comment]
ok. thanks for your help

**Comment by grishinoleg** [comment]
не за что

**Comment by nlevchuk** [comment]
:) У тебя есть информация когда lingz будет доступен?

**Comment by grishinoleg** [comment]
нет, он путешествует по китаю, так что у него редко бывает интернет сейчас. я написал ему

**Comment by nlevchuk** [comment]
Крутяк :)

**Pull request merged**
