### PR TITLE
remove options' noise from url

### PR DESCRIPTION
**Pull request by nlevchuk**
Hello

Need to clean options' noise from urls
alphabetical_paginate_noise_in_url

### CODE REVIEW

**Comment by nlevchuk** [comment]
If you haven't any questions I hope you can release new version ASAP. Thanks

**Comment by nlevchuk** [comment]
@lingz please reply for this PR

**Comment by grishinoleg** [comment]
He doesn't have access to the internet now. I merged an older PR, so I think there are merge conflicts now. Can you fix them and check if your changes pass the tests? I will merge it then

**Comment by nlevchuk** [comment]
@grishinoleg thank you for quick reply. I fixed and test passed.

**Comment by nlevchuk** [comment]
@grishinoleg thanks

**Pull request merged**
